
language: node_js # 设置语言

node_js: 10.16.0 # 设置相应版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容
branches:
    only:
        - hexo_source # 只监测hexo_source分支

install:
    - yarn global add hexo-cli # 安装hexo及插件
    - yarn
script:
    - hexo clean # 清除
    - hexo g # 生成

after_script:
    - git clone https://${GH_REF} .deploy_git
    - cd .deploy_git
    - git checkout master
    - cd ../
    - mv .deploy_git/.git/ ./public/
    - cd ./public
    - git config user.name $GIT_NAME
    - git config user.email $GIT_EMAIL
    - git add .
    - git commit -m "Travis CI Auto Builder $(date +%F' '%T) With $TRAVIS_COMMIT commit and Build $TRAVIS_BUILD_NUMBER"
# Github Pages
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# Coding Pages
    - git config user.name ${CODING_NAME}
    - git push --force --quiet "https://${CODING_NAME}:${CODING_TOKEN}@${CODING_REF}" master:master

env:
    global:
        - TZ=Asia/Shanghai 
        - GH_REF: github.com/${GIT_NAME}/${GIT_NAME}.github.io.git
        - CODING_REF: git.coding.net/${CODING_NAME}/${CODING_NAME}.git

notifications:
  email:
    recipients:
      - ${GIT_EMAIL}
    on_success: never # default: change
    on_failure: always # default: always