{%- if theme.show_post_end_message.enable %}
    <div>
        {% if not is_index %}
            <div style="text-align:center;color: #ccc;font-size:14px;">-------------本文结束<i class="fa fa-paw"></i>感谢您的阅读-------------</div>
        {% endif %}
    </div>
{%- endif %} 

{%- if theme.show_ad.enable %}
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
         (adsbygoogle = window.adsbygoogle || []).push({
              google_ad_client: "ca-pub-2993544047091842",
              enable_page_level_ads: true
         });
    </script>
{%- endif %} 
