name: Node CI

on:
  push:
    branches:
    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 10.16.0

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, hexo build
      run: |
        yarn global add hexo-cli
        yarn
        hexo clean
        hexo g
        